[package]
name = "solfunmeme_search_tantivy"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
tantivy = { version = "0.24", features = ["mmap", "lz4-compression"] }
solfunmeme_function_analysis = { path = "../solfunmeme_function_analysis" }
