[package]
name = "solfunmeme_search_tantivy"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = { path = "../../vendor/tantivy" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"
bincode = "1.3"

solfunmeme_function_analysis = { path = "../solfunmeme_function_analysis" }