[package]
name = "solana_airdrop_service_plugin"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
solana-airdrop-service = { path = "../../vendor/solana-airdrop-service" }
