[package]
name = "rdf_output"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
shared_analysis_types = { path = "../shared_analysis_types" }
solfunmeme_rdf_utils = { path = "../solfunmeme_rdf_utils" }
anyhow = "1.0"
