[package]
name = "solfunmeme_tantivy_report"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
solfunmeme_search_tantivy = { path = "../solfunmeme_search_tantivy" }
