[package]
name = "zos_cli_modules"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
solfunmeme_core_utils = { path = "../solfunmeme_core_utils" }
solfunmeme_serde_utils = { path = "../solfunmeme_serde_utils" }
serde = { version = "1.0", features = ["derive"] }
