[package]
name = "solfunmeme_embedding"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
rand = "0.8"
candle-core = { version = "0.9.1", default-features = false }
candle-nn = { version = "0.9.1", default-features = false }
candle-transformers = { version = "0.9.1", default-features = false }
hf-hub = { version = "0.3", default-features = false, features = ["online"] }
tokenizers = "0.15"
sophia_api = "0.8"
sophia_inmem = "0.8"
sophia_turtle = "0.8"
solfunmeme_clifford = { path = "../solfunmeme_clifford" }