[package]
name = "quickwit_plugin"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
quickwit-rest-client = { path = "../../vendor/quickwit/quickwit/quickwit-rest-client" }
