[package]
name = "solfunmeme_solana_deps"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
solana-sdk = { version = "2.3.0" }
solana-transaction-error = { version = "3.0.0-canary.7040146", features=["serde"] }
solana-system-interface = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.12"
bs58 = "0.5.1"
bincode = "1.3.3"
borsh = "0.10.4"
borsh-derive = "0.10.4"
sha2 = "0.10.9"
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }
curve25519-dalek = "4.1.3"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
uuid = { version = "1.17.0", features = ["v4", "js", "rng-getrandom", "rng-rand"] }
