[package]
name = "solfunmeme_core_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2.3"
sha2 = "0.10"
rand = "0.8.5"
rand_core = { version = "0.6.4", features = ["std"] }