[package]
name =  "rrust_kontekst"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = "2.0.104"
rrust_kontekst_base = { path = "../rrust_kontekst_base" }

[lib]
name = "rrust_kontekst"
path = "src/lib.rs"
proc-macro = true