[package]
name = "solfunmeme_tarot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
solfunmeme_models = { path = "../solfunmeme_models" }
solfunmeme_lean4 = { path = "../solfunmeme_lean4" }
solfunmeme_rdf_utils = { path = "../solfunmeme_rdf_utils" }


libloading = "0.8.3"
