[package]
name = "duplicate-check"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
walkdir = "2.5.0"
sha2 = "0.10.9"
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tantivy = { version = "0.24", features = ["mmap", "lz4-compression"] }
anyhow = "1.0"

[[bin]]
name = "duplicate_check"
path = "duplicate_check.rs"

[[bin]]
name = "index_exporter"
path = "index_exporter.rs" 