[package]
name = "solfunmeme_solana_data"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
anyhow = "1.0"
borsh = "0.10"
sha2 = "0.10"
tracing = "0.1"
solana-client = { version = "2.3", default-features = false }
solana-sdk = { version = "2.3", default-features = false }
solana-program = { version = "2.3", features = ["borsh"] }
