[package]
name = "solfunmeme_input_fs"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"

[dependencies]
walkdir = "2.3"
anyhow = "1.0"
shared_analysis_types = { path = "../shared_analysis_types" }
